/* tslint:disable */
/* eslint-disable */
/**
 * Overmind API
 * API for managing your Overmind account
 *
 * The version of the OpenAPI document: 0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * A source that is capable of discovering items
 * @export
 * @interface Source
 */
export interface Source {
    /**
     * The descriptive name of the source
     * @type {string}
     * @memberof Source
     */
    descriptiveName?: string;
    /**
     * Unique ID of the source
     * @type {string}
     * @memberof Source
     */
    sourceId?: string;
    /**
     * The name of the nats JWT that has been generated for this source
     * @type {string}
     * @memberof Source
     */
    tokenName?: string;
    /**
     * When the NATS JWT expires (unix time)
     * @type {number}
     * @memberof Source
     */
    tokenExpiry?: number;
    /**
     * The public NKey associated with the NATS JWT
     * @type {string}
     * @memberof Source
     */
    publicNkey?: string;
    /**
     * What source to configure. Currently either "stdlib" or "aws"
     * @type {string}
     * @memberof Source
     */
    type?: string;
    /**
     * Config for this source. See the source documentation for what source-specific config is available/required
     * @type {{ [key: string]: string; }}
     * @memberof Source
     */
    config?: { [key: string]: string; };
}

/**
 * Check if a given object implements the Source interface.
 */
export function instanceOfSource(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SourceFromJSON(json: any): Source {
    return SourceFromJSONTyped(json, false);
}

export function SourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): Source {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'descriptiveName': !exists(json, 'descriptive_name') ? undefined : json['descriptive_name'],
        'sourceId': !exists(json, 'source_id') ? undefined : json['source_id'],
        'tokenName': !exists(json, 'token_name') ? undefined : json['token_name'],
        'tokenExpiry': !exists(json, 'token_expiry') ? undefined : json['token_expiry'],
        'publicNkey': !exists(json, 'public_nkey') ? undefined : json['public_nkey'],
        'type': !exists(json, 'type') ? undefined : json['type'],
        'config': !exists(json, 'config') ? undefined : json['config'],
    };
}

export function SourceToJSON(value?: Source | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'descriptive_name': value.descriptiveName,
        'source_id': value.sourceId,
        'token_name': value.tokenName,
        'token_expiry': value.tokenExpiry,
        'public_nkey': value.publicNkey,
        'type': value.type,
        'config': value.config,
    };
}

