/* tslint:disable */
/* eslint-disable */
/**
 * Overmind API
 * API for managing your Overmind account
 *
 * The version of the OpenAPI document: 0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TokenRequestData
 */
export interface TokenRequestData {
    /**
     * The Public NKey of the user that is requesting a token
     * @type {string}
     * @memberof TokenRequestData
     */
    userPubKey: string;
    /**
     * Friendly user name
     * @type {string}
     * @memberof TokenRequestData
     */
    userName: string;
}

/**
 * Check if a given object implements the TokenRequestData interface.
 */
export function instanceOfTokenRequestData(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "userPubKey" in value;
    isInstance = isInstance && "userName" in value;

    return isInstance;
}

export function TokenRequestDataFromJSON(json: any): TokenRequestData {
    return TokenRequestDataFromJSONTyped(json, false);
}

export function TokenRequestDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenRequestData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'userPubKey': json['user_pub_key'],
        'userName': json['user_name'],
    };
}

export function TokenRequestDataToJSON(value?: TokenRequestData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'user_pub_key': value.userPubKey,
        'user_name': value.userName,
    };
}

